// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { FaArrowsUpDownLeftRight, FaBuildingShield, FaBullseye, FaClockRotateLeft, FaCompass, FaEye, FaFeather, FaFileLines, FaHeadset, FaHouse, FaHouseChimney, FaHouseChimneyCrack, FaLayerGroup, FaLifeRing, FaLink, FaMagnifyingGlass, FaPalette, FaPhone, FaRobot, FaRotateLeft, FaScaleBalanced, FaShieldHalved, FaTree, FaTriangleExclamation, FaUniversalAccess, FaWandMagicSparkles, FaXmark } from 'react-icons/fa6';
import { LuArrowRight, LuArrowUpRight, LuBookOpen, LuChevronRight, LuContact, LuGithub, LuGlobe, LuImage, LuLinkedin, LuMail, LuMapPin, LuPhone, LuSettings, LuTwitter } from 'react-icons/lu';
import { FaBuilding } from 'react-icons/fa';
import { SiFacebook } from 'react-icons/si';

export const iconMap = {
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:building-shield': FaBuildingShield,
  'fa6:bullseye': FaBullseye,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:house': FaHouse,
  'fa6:house-chimney': FaHouseChimney,
  'fa6:house-chimney-crack': FaHouseChimneyCrack,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:magnifying-glass': FaMagnifyingGlass,
  'fa6:palette': FaPalette,
  'fa6:phone': FaPhone,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:tree': FaTree,
  'fa6:triangle-exclamation': FaTriangleExclamation,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'fa:building': FaBuilding,
  'lu:arrow-right': LuArrowRight,
  'lu:arrow-up-right': LuArrowUpRight,
  'lu:book-open': LuBookOpen,
  'lu:chevron-right': LuChevronRight,
  'lu:contact': LuContact,
  'lu:github': LuGithub,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:linkedin': LuLinkedin,
  'lu:mail': LuMail,
  'lu:map-pin': LuMapPin,
  'lu:phone': LuPhone,
  'lu:settings': LuSettings,
  'lu:twitter': LuTwitter,
  'si:facebook': SiFacebook,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
