// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { FaArrowRightLong, FaArrowsUpDownLeftRight, FaBandage, FaBrush, FaBuildingShield, FaBullseye, FaClipboardCheck, FaClockRotateLeft, FaCompass, FaEye, FaFeather, FaFileLines, FaHeadset, FaHouseChimney, FaLayerGroup, FaLifeRing, FaLink, FaLocationDot, FaPalette, FaPhone, FaRoad, FaRobot, FaRotateLeft, FaScaleBalanced, FaScrewdriverWrench, FaShieldHalved, FaStar, FaUniversalAccess, FaWandMagicSparkles, FaXmark } from 'react-icons/fa6';
import { LuArrowRight, LuArrowUpRight, LuBookOpen, LuChevronLeft, LuChevronRight, LuContact, LuGlobe, LuImage, LuMail, LuMapPin, LuPhone, LuSettings } from 'react-icons/lu';
import { SiFacebook, SiInstagram, SiYoutube } from 'react-icons/si';

export const iconMap = {
  'fa6:arrow-right-long': FaArrowRightLong,
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:bandage': FaBandage,
  'fa6:brush': FaBrush,
  'fa6:building-shield': FaBuildingShield,
  'fa6:bullseye': FaBullseye,
  'fa6:clipboard-check': FaClipboardCheck,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:house-chimney': FaHouseChimney,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:location-dot': FaLocationDot,
  'fa6:palette': FaPalette,
  'fa6:phone': FaPhone,
  'fa6:road': FaRoad,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:screwdriver-wrench': FaScrewdriverWrench,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:star': FaStar,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'lu:arrow-right': LuArrowRight,
  'lu:arrow-up-right': LuArrowUpRight,
  'lu:book-open': LuBookOpen,
  'lu:chevron-left': LuChevronLeft,
  'lu:chevron-right': LuChevronRight,
  'lu:contact': LuContact,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:mail': LuMail,
  'lu:map-pin': LuMapPin,
  'lu:phone': LuPhone,
  'lu:settings': LuSettings,
  'si:facebook': SiFacebook,
  'si:instagram': SiInstagram,
  'si:youtube': SiYoutube,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
